export type CatalogEntry = {
  id: string;
  group: string;
  frameName: string;
  stateLabel: string;
  description: string;
};

/** DEV-001 registers only the bootstrap placeholder row. Canonical MVP rows land with UI Issues. */
export const catalogEntries: CatalogEntry[] = [
  {
    id: 'bootstrap-shell',
    group: '00 시작',
    frameName: 'DEV_Bootstrap_Shell',
    stateLabel: 'Content',
    description:
      'Non-canonical bootstrap placeholder proving catalog shell rendering without auth/DB.',
  },
  {
    id: '00-splash-default',
    group: '00 시작',
    frameName: '00_Splash',
    stateLabel: 'Default',
    description:
      'Canonical splash: brand-primary background and centered white Tampin wordmark only.',
  },
  {
    id: 'data-layer-health',
    group: '00 시작',
    frameName: 'DEV_Data_Layer_Health',
    stateLabel: 'ReadOnly',
    description:
      'Read-only SQLite initialization status and schema version observability.',
  },
  {
    id: '01a-login-ready',
    group: '01 로그인',
    frameName: '01A_Login',
    stateLabel: 'Ready',
    description:
      'Canonical Login with stacked provider CTAs ready for development bypass sign-in.',
  },
  {
    id: '01a-login-unavailable',
    group: '01 로그인',
    frameName: '01A_Login',
    stateLabel: 'Unavailable',
    description:
      'Release/non-dev provider CTAs visibly unavailable and fail closed.',
  },
  {
    id: '01a-login-busy',
    group: '01 로그인',
    frameName: '01A_Login',
    stateLabel: 'Busy',
    description:
      'Provider CTAs disabled while sign-in is in progress to prevent double press.',
  },
  {
    id: '01a1-login-error-dialog-reference',
    group: '01 로그인',
    frameName: '01A1_Login_Error_Overlay_Cases',
    stateLabel: 'ErrorDialogReference',
    description:
      'Component-state reference overlay; not a navigation route. General failure dialog shown.',
  },
  {
    id: '01c-basic-info-default',
    group: '01 로그인',
    frameName: '01C_Basic_Info',
    stateLabel: 'Default',
    description:
      'First-run Basic Info default: no sex, empty DOB placeholder, Terms unchecked, disabled CTA.',
  },
  {
    id: '01c1-basic-info-error',
    group: '01 로그인',
    frameName: '01C1_Basic_Info_Error',
    stateLabel: 'Error',
    description:
      'Invalid DOB inline error with disabled CTA until all required fields are valid.',
  },
  {
    id: '01c2-basic-info-focused',
    group: '01 로그인',
    frameName: '01C2_Basic_Info_Focused',
    stateLabel: 'Focused',
    description: 'DOB field focused with filled value; other requirements still incomplete.',
  },
  {
    id: '01c3-basic-info-filled',
    group: '01 로그인',
    frameName: '01C3_Basic_Info_Filled',
    stateLabel: 'Filled',
    description:
      'Filled valid DOB without sex/Terms; CTA remains disabled until all requirements pass.',
  },
  {
    id: '01c4-basic-info-disabled',
    group: '01 로그인',
    frameName: '01C4_Basic_Info_Disabled',
    stateLabel: 'Disabled',
    description: 'DOB input disabled representative state at 30% opacity.',
  },
  {
    id: '02a-routine-main-with-routines',
    group: '02 루틴',
    frameName: '02A_Routine_Main',
    stateLabel: 'WithRoutines',
    description:
      'Routine main with quick actions, PPL folder/cards, and floating bottom app bar.',
  },
  {
    id: '02b-routine-main-empty',
    group: '02 루틴',
    frameName: '02B_Routine_Main_Empty',
    stateLabel: 'Empty',
    description:
      'Routine main empty state: identical quick actions with no routine folders.',
  },
  {
    id: '02d-routine-detail-default',
    group: '02 루틴',
    frameName: '02D_Routine_Detail',
    stateLabel: 'Default',
    description:
      'Scrollable routine detail with summary strip, four exercise set cards, and start CTA.',
  },
  {
    id: '02e-folder-entry-selected',
    group: '02 루틴',
    frameName: 'DEV_Routine_Folder_Entry',
    stateLabel: 'ExistingFolderSelected',
    description:
      'Mock-phase folder-first entry with an existing folder selected before routine creation.',
  },
  {
    id: '02e-folder-entry-new-name',
    group: '02 루틴',
    frameName: 'DEV_Routine_Folder_Entry',
    stateLabel: 'NewFolderNamed',
    description:
      'Mock-phase folder-first entry with a deterministic new folder name.',
  },
  {
    id: '02e-routine-create-folder-prefilled',
    group: '02 루틴',
    frameName: '02E_Routine_Create',
    stateLabel: 'FolderPrefilled',
    description:
      'Current Figma routine-create state reached immediately after folder selection.',
  },
  {
    id: '04a-search-default',
    group: '04 운동',
    frameName: '04A_Search',
    stateLabel: 'Default',
    description: 'Exercise add/search root with recent and all-exercise lists.',
  },
  {
    id: '04a-filter-equipment',
    group: '04 운동',
    frameName: '04A_Filter_Equipment_Page',
    stateLabel: 'AllSelected',
    description: 'Full-page single-select equipment filter with 전체 selected.',
  },
  {
    id: '04a-filter-body-part',
    group: '04 운동',
    frameName: '04A_Filter_BodyPart_Page',
    stateLabel: 'AllSelected',
    description: 'Full-page single-select body-part filter with 전체 selected.',
  },
  {
    id: '04b-search-selected',
    group: '04 운동',
    frameName: '04B_Search_Selected',
    stateLabel: 'Selected',
    description: 'Search with selected chips and N개 운동 추가 footer.',
  },
  {
    id: '04c-search-empty',
    group: '04 운동',
    frameName: '04C_Search_Empty',
    stateLabel: 'Empty',
    description: 'No-result search with 직접 운동 만들기 empty action.',
  },
  {
    id: '04d-detail-info',
    group: '04 운동',
    frameName: '04D_Exercise_Detail_Info',
    stateLabel: 'Info',
    description: 'Bench press info tab with media, metadata, method, checkpoints.',
  },
  {
    id: '04d-detail-history',
    group: '04 운동',
    frameName: '04D_Exercise_Detail_History',
    stateLabel: 'HistoryWeightReps',
    description: 'Weight+reps history tab with native kg/rep values.',
  },
  {
    id: '04d-detail-growth',
    group: '04 운동',
    frameName: '04D_Exercise_Detail_Growth',
    stateLabel: 'GrowthWeightReps',
    description: 'Weight+reps growth with Figma trend chart and personal-best table.',
  },
  {
    id: '04d-detail-history-reps',
    group: '04 운동',
    frameName: '04D_Exercise_Detail_History_Reps',
    stateLabel: 'HistoryReps',
    description: 'Reps-only history; no fake kg.',
  },
  {
    id: '04d-detail-growth-reps',
    group: '04 운동',
    frameName: '04D_Exercise_Detail_Growth_Reps',
    stateLabel: 'GrowthReps',
    description: 'Reps-only growth chart (반복 변화) and max-rep personal best.',
  },
  {
    id: '04d-detail-history-duration',
    group: '04 운동',
    frameName: '04D_Exercise_Detail_History_Duration',
    stateLabel: 'HistoryDuration',
    description: 'Duration history using native time values.',
  },
  {
    id: '04d-detail-growth-duration',
    group: '04 운동',
    frameName: '04D_Exercise_Detail_Growth_Duration',
    stateLabel: 'GrowthDuration',
    description: 'Duration growth chart (시간 변화) and longest-time personal best.',
  },
  {
    id: '04d-detail-history-assisted',
    group: '04 운동',
    frameName: '04D_Exercise_Detail_History_Assisted',
    stateLabel: 'HistoryAssisted',
    description: 'Assisted history showing assistance kg + reps.',
  },
  {
    id: '04d-detail-growth-assisted',
    group: '04 운동',
    frameName: '04D_Exercise_Detail_Growth_Assisted',
    stateLabel: 'GrowthAssisted',
    description: 'Assisted growth chart (보조중량 변화); lower assistance is harder.',
  },
  {
    id: '04d-detail-history-empty',
    group: '04 운동',
    frameName: '04D_Exercise_Detail_History_Empty',
    stateLabel: 'HistoryEmpty',
    description: 'History tab empty state with no fake records.',
  },
  {
    id: '04d-detail-growth-empty',
    group: '04 운동',
    frameName: '04D_Exercise_Detail_Growth_Empty',
    stateLabel: 'GrowthEmpty',
    description: 'Growth tab empty state with no fake trend.',
  },
  {
    id: '04d-detail-growth-insufficient',
    group: '04 운동',
    frameName: '04D_Exercise_Detail_Growth_Insufficient',
    stateLabel: 'GrowthInsufficient',
    description: 'Chart card empty-in-card copy plus personal-best rows.',
  },
  {
    id: '04e-custom-create',
    group: '04 운동',
    frameName: '04E_Custom_Create',
    stateLabel: 'Invalid',
    description: 'Custom create with empty required fields and disabled save.',
  },
  {
    id: '04e-custom-create-valid',
    group: '04 운동',
    frameName: '04E_Custom_Create_Valid',
    stateLabel: 'Valid',
    description: 'Custom create with required fields filled and save enabled.',
  },
  {
    id: '04f-custom-edit',
    group: '04 운동',
    frameName: '04F_Custom_Edit',
    stateLabel: 'Unlocked',
    description: 'Custom edit without history lock; recording type remains selectable.',
  },
  {
    id: '04f-custom-edit-history-locked',
    group: '04 운동',
    frameName: '04F_Custom_Edit_HistoryLocked',
    stateLabel: 'HistoryLocked',
    description: 'Custom edit with read-only recording type and persistent hint.',
  },
  {
    id: '04h-attachment-selection',
    group: '04 운동',
    frameName: '04H_Exercise_Attachment_Selection',
    stateLabel: 'Sheet',
    description: 'Attachment/grip selection overlay on the search shell.',
  },
  {
    id: '04h-attachment-input',
    group: '04 운동',
    frameName: '04H_Custom_Attachment_Input',
    stateLabel: 'DirectInput',
    description: 'Figma attachment input: 목록에 없는 손잡이 이름 / 사용하기.',
  },
  {
    id: '04i-custom-equipment',
    group: '04 운동',
    frameName: '04I_Custom_Equipment_Select',
    stateLabel: 'CableSelected',
    description: 'Custom-exercise equipment picker.',
  },
  {
    id: '04j-custom-primary-muscle',
    group: '04 운동',
    frameName: '04J_Custom_PrimaryMuscle_Select',
    stateLabel: 'BackSelected',
    description: 'Custom-exercise primary muscle picker.',
  },
  {
    id: '04k-custom-secondary-muscle',
    group: '04 운동',
    frameName: '04K_Custom_SecondaryMuscle_Select',
    stateLabel: 'BicepsSelected',
    description: 'Custom-exercise secondary muscle picker with 이두 selected.',
  },
  {
    id: '04l-custom-recording-type',
    group: '04 운동',
    frameName: '04L_Custom_RecordingType_Select',
    stateLabel: 'WeightRepsSelected',
    description: 'Four MVP recording-type options only.',
  },
  {
    id: '04ef-unsaved-confirm',
    group: '04 운동',
    frameName: '04EF_Custom_Unsaved_Confirm',
    stateLabel: 'UnsavedDialog',
    description: 'Leave-without-save dialog over a dirty custom-create form.',
  },
  {
    id: '04f-delete-confirm',
    group: '04 운동',
    frameName: '04F_Custom_Delete_Confirm',
    stateLabel: 'DeleteDialog',
    description: 'Delete confirm dialog; completed history remains.',
  },
  {
    id: '05a-workout-weight',
    group: '05 운동 중',
    frameName: '05A_Workout_Weight',
    stateLabel: 'Logging',
    description: 'Active workout shell with elapsed header and set table.',
  },
  {
    id: '05a-workout-scrolled',
    group: '05 운동 중',
    frameName: '05A_Workout_Weight_Scrolled_3rdExercise',
    stateLabel: 'Scrolled',
    description: 'Same 05A shell at scrolled third-exercise offset. Not a route.',
  },
  {
    id: '05i-workout-menu',
    group: '05 운동 중',
    frameName: '05I_Workout_Menu',
    stateLabel: 'HeaderMenu',
    description: 'Compact anchored header menu: 운동 종료 / 운동 추가 / 타이머.',
  },
  {
    id: '05j-reorder',
    group: '05 운동 중',
    frameName: '05J_Reorder',
    stateLabel: 'Reorder',
    description: 'Exercise order editor. Handle press moves a row down in mock.',
  },
  {
    id: '05k-end-incomplete',
    group: '05 운동 중',
    frameName: '05K_End_Incomplete',
    stateLabel: 'EndDialog',
    description: 'End workout while planned sets remain.',
  },
  {
    id: '05l-end-complete',
    group: '05 운동 중',
    frameName: '05L_End_Complete',
    stateLabel: 'EndDialog',
    description: 'End workout after all planned sets are complete.',
  },
  {
    id: '05m-discard',
    group: '05 운동 중',
    frameName: '05M_Discard',
    stateLabel: 'DiscardDialog',
    description: 'Discard current unsaved session. No 05I row in current Figma.',
  },
  {
    id: '05o-update-routine',
    group: '05 운동 중',
    frameName: '05O_Workout_UpdateRoutine',
    stateLabel: 'UpdateDialog',
    description: '오늘만 적용 / 루틴에 저장 after structural session change.',
  },
  {
    id: '05g-replace-suggest',
    group: '05 운동 중',
    frameName: '05G_Exercise_Replace_Suggest',
    stateLabel: 'Unselected',
    description: 'Replacement first batch; 선택 완료 disabled.',
  },
  {
    id: '05h-replace-selected',
    group: '05 운동 중',
    frameName: '05H_Exercise_Replace_Selected',
    stateLabel: 'Selected',
    description: 'Replacement first batch with one radio selected.',
  },
  {
    id: '05g2-replace-second',
    group: '05 운동 중',
    frameName: '05G2_Exercise_Replace_SecondBatch',
    stateLabel: 'SecondBatch',
    description: 'Second secured replacement group. Cycles with 다른 운동 보기.',
  },
  {
    id: '05p-replace-delete',
    group: '05 운동 중',
    frameName: '05P_Exercise_Replace_DeleteConfirm',
    stateLabel: 'DeleteDialog',
    description: 'Replace after completed sets in the current session only.',
  },
  {
    id: '05n-other-incomplete',
    group: '05 운동 중',
    frameName: '05N_Workout_OtherRoutine_Incomplete',
    stateLabel: 'SwitchDialog',
    description: 'Start another routine while current planned work is incomplete.',
  },
  {
    id: '05n-other-complete',
    group: '05 운동 중',
    frameName: '05N_Workout_OtherRoutine_Complete',
    stateLabel: 'SwitchDialog',
    description: 'Start another routine after current planned sets complete.',
  },
  {
    id: '05f-rest-timer',
    group: '05 운동 중',
    frameName: '05F_Workout_RestTimer',
    stateLabel: 'RestSheet',
    description: 'Automatic rest bottom sheet with ±15 and 휴식 건너뛰기.',
  },
  {
    id: '05q-manual-idle',
    group: '05 운동 중',
    frameName: '05Q_ManualTimer_Idle',
    stateLabel: 'Idle',
    description: 'Manual timer idle 01:30 / 타이머 시작.',
  },
  {
    id: '05q-manual-running',
    group: '05 운동 중',
    frameName: '05Q_ManualTimer_Running',
    stateLabel: 'Running',
    description: 'Manual timer running / 일시정지.',
  },
  {
    id: '05q-manual-paused',
    group: '05 운동 중',
    frameName: '05Q_ManualTimer_Paused',
    stateLabel: 'Paused',
    description: 'Manual timer paused / 초기화 / 계속 진행.',
  },
];
